apiVersion: 1

groups:
  - orgId: 1
    name: infrastructure-alerts
    folder: Infrastructure Alerts
    interval: 30s
    rules:
      - uid: high_cpu_app1
        title: App1 High CPU
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: sum(rate(container_cpu_usage_seconds_total{name=~".*app1.*"}[5m])) > 0.05
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          summary: "CPU alta no app1"
          description: "O uso de CPU do container app1 passou de 0.05 core médio nos últimos 5 minutos."
        labels:
          severity: warning
          service: app1
          alerttype: infrastructure

      - uid: high_memory_app2
        title: App2 High Memory
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: container_memory_usage_bytes{name=~".*app2.*"} / 1024 / 1024 > 50
              instant: true
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
        noDataState: NoData
        execErrState: Error
        for: 1m
        annotations:
          summary: "Memória alta no app2"
          description: "O uso de memória do container app2 passou de 50 MB."
        labels:
          severity: warning
          service: app2
          alerttype: infrastructure